### PR TITLE
Grule issue #431. update go-git to v5.

### PR DESCRIPTION
**Pull request by davidsonff**
Update to go-git v5

### CODE REVIEW

**Comment by laurenfr** [comment]
Thanks for doing this--definitely fairly urgent security-wise, so a timely approval & release from a maintainer would be most appreciated 🙏

**Review by GreyBouton — APPROVED** [review]

**Comment by GreyBouton** [comment]
Everything looks good. I just got a call from corporate and we need to ship this asap.

**Comment by juburr** [comment]
@newm4n can you assist?

**Comment by vamsitadikonda-discovery** [comment]
Looks like it still needs an approval.

**Comment by GreyBouton** [comment]
@newm4n Everything checks out, let's go ahead and merge this. My organization already forked this code to fulfill the dependency but we would like to go back to this one. If we do not get this done, the UN may get involved and we do not want that.

**Comment by niallnsec** [comment]
I've been away from the project for a while, but it seems the other maintainers are busy and I have some time at the moment.

I agree this vulnerability is worthy of being considered critical. There don't seem to be any external effects to upgrading the go-git dependency which makes this nice and simple.

LGTM

**Review by niallnsec — APPROVED** [review]

**Comment by procommand** [comment]
The codes quality overall deviates from industry norms yet this sort of work is commendable yet also punishable by a probationary period not sure what to say except it is what it is as long as it works right? Duck tape strategy?

**Pull request merged**
