### PR TITLE
feat:short-circuit evaluation

### PR DESCRIPTION
**Pull request by vlean**
fix: #127 
support short-circuit evaluation

### CODE REVIEW

**Comment by newm4n** [comment]
Hi @vlean, 
Thanks alot for the PR, 
However, could you ensure that all the test runs without problem prior submitting PR.
`make test` should do fine.

**Comment by vlean** [comment]
> Hi @vlean,
> Thanks alot for the PR,
> However, could you ensure that all the test runs without problem prior submitting PR.
> `make test` should do fine.

ok, I have recommitted the code and passed the test.

**Comment by vasubabu-Sixt** [comment]
@vlean - Can you add one/more test (may be the one you demoed in the issue) to examples directory?

**Comment by jinagamvasubabu** [comment]
@vlean can you add one/more test (may be the one you demoed in the [issue](https://github.com/hyperjumptech/grule-rule-engine/issues/127)) to examples directory ?

**Comment by jinagamvasubabu** [comment]
Ignore the above comment, this is not a feature to add it to the examples directory. My Bad. 

PR Looks fine for me

**Review by newm4n — APPROVED** [review]
This looks solid.
LGTM

**Pull request merged**
