### PR TITLE
Add supporting zap logger in grule-rule-engine

### PR DESCRIPTION
**Pull request by krupyansky**

### CODE REVIEW

**Comment by newm4n** [comment]
Hi @krupyansky 

This is great and a very nice addition to the library.
Could you update your branch as its now out-of-date. 
And one more thing, as your proposed changes have a potential break to other Grule users already using the original logging mechanism, could you help me to add small note that I can use in the "change note" for this particular new addition on the next release?

**Comment by krupyansky** [comment]
Hi @newm4n 

Thanks for the kind words!

By default, grule-rule-engine and its subpackages use the logrus logger, which is initialized in the logger subpackage.

The ability to pass a logger (zap or logrus) to subpackages that is initialized in your applications (usually in main.go) has been added.

In each subpackage antlr, ast, builder, engin, the **SetLogger (externalLog interface{})** function was added. 
It can be passed a logger instance (zap or logrus) to be used by the subpackage.

The SetLogLevel() function from the logger package has been changed. 
Now it is not tied to logrus levels, but uses the levels defined in the logger subpackage of the current library.

**Comment by newm4n** [comment]
Great note, now could you please update your branch to the base branch so I could run the test pipeline with most recent changes.

**Comment by krupyansky** [comment]
Updated

**Review by newm4n — APPROVED** [review]

**Comment by newm4n** [comment]
@krupyansky Its merged and will be included on the next release soon.

**Comment by krupyansky** [comment]
@newm4n thanks!
Let's wait for the release)

**Pull request merged**
