### PR TITLE
Fix Goroutine leak when ExecuteContext ctx value is not cancelled

### PR DESCRIPTION
**Pull request by niallnsec**
Hello,

In the engine ExecuteContext function, there is a goroutine created to listen for cancellation of the passed in context. The only condition under which this routine exits is the cancellation of the context. This means that if the caller does not cancel the context after execution is complete, the goroutine will remain stalled indefinitely. This exact scenario occurs when calling Execute since it passes in an instance of context.Background().

To fix the issue, this PR removes the goroutine entirely and instead checks the value of ctx.Err() on each cycle of the engine. When the context is cancelled Err() will return a non-nil value which should result in the same behaviour offered by the goroutine approach but with much less overhead.

Thanks,
Niall

### CODE REVIEW

**Comment by newm4n** [comment]
Taking from sample [here](https://golang.org/pkg/context/#example_WithCancel)
couldn't we just changed the select to

```go
		case <-ctx.Done():
			contextError = ctx.Err()
			contextCanceled = true
			return   // returning not to leak the goroutine
		}
```

**Comment by niallnsec** [comment]
Looking at that sample, I think the key there is their deferred call to cancel since that is what is what triggers the select statement to return. 
In the ExecuteContext function, since we don't have control over the CTX value passed in we would have to wrap it with a call to context.WithCancel to get the same behaviour. But even if we did that, the creation of a new context plus a goroutine is quite a bit more overhead than checking ctx.Err in each loop iteration. I believe if you look at the implementation of ctx.Err it pretty much just returns an unexported variable so will be very fast.

**Comment by niallnsec** [comment]
Also the approach of checking ctx.Err() within a potentially long running loop is quite an idiomatic pattern, for example, here are a couple of use of the same pattern in Googles GRPC Go library: 
https://github.com/grpc/grpc-go/blob/7745e521ff6104ff816d2826de86baa5b8051d03/credentials/tls/certprovider/meshca/plugin.go#L151
https://github.com/grpc/grpc-go/blob/dc49de8acd511e4d47ad0cbf58bd77f4775c165f/health/client.go#L70

**Review by newm4n — APPROVED** [review]
This looks good.

**Comment by niallnsec** [comment]
Sweet, thanks :)

**Pull request merged**
